In [1]:
import scipy.linalg as lng 
import numpy as np
import time
N = 5
A = np.random.random((N,N))
k = np.arange(N)
b = np.zeros(N)

for t in np.linspace(0.,10.,100):
    b = k/(1.+ k * t) 
    res1 = lng.solve(A,b)
    print(res1)

lu,piv = lng.lu_factor(A)
for t in np.linspace(0.,10.,100):
    b = k/(1.+ k * t) 
    res2 = lng.lu_solve((lu,piv), b)
    print(res2)

A2 = lng.inv(A)
for t in np.linspace(0.,10.,100):
    b = k/(1.+ k * t) 
    res3 = np.dot(A2,b) 
    print(res3)

start_time =time.time()
for i in  range (10000):
    lng.solve(A,b)

print(time.time()-start_time)


start_time =time.time()
for i in  range (10000):
    lng.lu_solve((lu,piv), b)

    
print(time.time()-start_time)

start_time =time.time()
for i in  range (10000):
    np.dot(A2,b)
    
print(time.time()-start_time)


[  3.40044243   8.35107337 -13.35924031  -1.77296644   8.28623583]
[ 2.84376794  6.16501418 -9.76029309 -1.54282913  5.92205525]
[ 2.49548123  4.89616306 -7.75100671 -1.39375438  4.63217244]
[ 2.2439216   4.06572718 -6.46277358 -1.27810135  3.81827128]
[ 2.04797883  3.47922492 -5.56237881 -1.18223636  3.25640732]
[ 1.88839325  3.04253113 -4.89491165 -1.10038591  2.84414721]
[ 1.75459243  2.7044974  -4.37861579 -1.02932618  2.5280609 ]
[ 1.640102    2.43492098 -3.96624025 -0.96693083  2.27754981]
[ 1.54063664  2.21481093 -3.62853973 -0.91166255  2.07381875]
[ 1.45319446  2.03162277 -3.34641712 -0.86235162  1.90467537]
[ 1.37558142  1.87673416 -3.10685365 -0.81808025  1.76185729]
[ 1.3061408   1.74402122 -2.90065532 -0.77811348  1.63956146]
[ 1.24358905  1.62901339 -2.72113519 -0.74185391  1.53358875]
[ 1.186911    1.52836985 -2.56330698 -0.70881015  1.44082311]
[ 1.13528987  1.43954324 -2.42337233 -0.67857402  1.3589017 ]
[ 1.08805911  1.36055684 -2.29838387 -0.6508035   1.28599904]
[ 1